###
POST https://localhost:7018/api/V01/Authenticate/login
content-type: application/json

{
  "username": "jimmy",
  "password": "nordin_A1"
}
###
POST https://localhost:7018/api/V01/Authenticate/register
content-type: application/json

{
  "username": "jimmy2",
  "email": "jimmy2@example.com",
  "password": "nordin_A1"
}
###
GET https://localhost:7018/api/V01/Advert/GetAllAdverts
###
GET https://localhost:7018/api/V01/Advert/GetAdvertById/e253e92d-efd2-40a6-9289-08da9d96df53
###

Post https://localhost:7018/api/V01/Advert/AddAdvert
content-type: application/json

{
  "userId": "1DDCEAEE-95DC-4650-3222-08DA9D96DF47",
  "name": "NalleKalle",
  "age": 120,
  "race": "string",
  "sex": "string",
  "personallity": "string",
  "rentPeriod": 120,
  "grade": 5,
  "review": "string",
  "imageUrls": "string"
}
###
DELETE https://localhost:7018/api/V01/Advert/DeleteAdvertById/8362AF28-6A6F-41D5-928B-08DA9D96DF53
###
PATCH  https://localhost:7018/api/V01/Advert/UpdateAdvertById/BA08EBA2-BAE6-4ED2-928C-08DA9D96DF53
content-type: application/json

{
  "userId": "B7D95522-B12F-4DAD-3223-08DA9D96DF47",
  "name": "HejDåDå",
  "age": 120,
  "race": "string",
  "sex": "string",
  "personallity": "string",
  "rentPeriod": 120,
  "grade": 5,
  "review": "string",
  "imageUrls": "string"
}
###
GET https://localhost:7018/api/V01/User/GetAllUsers
###
GET https://localhost:7018/api/V01/User/GetUserById/1ddceaee-95dc-4650-3222-08da9d96df47
###
POST https://localhost:7018/api/V01/User/AddUser
content-type: application/json

{
  "alias": "asdf",
  "email": "asdf@example.com",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "adverts": []
}

###
DELETE https://localhost:7018/api/V01/User/DeleteUserById/E2CAEFC4-A65E-4CAD-E5E1-08DA9DAB87C6
###

PATCH  https://localhost:7018/api/V01/User/UpdateUser/DDA0F0EC-7073-4822-3225-08DA9D96DF47
content-type: application/json

{
  "alias": "string",
  "email": "julgran2@example.com",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "adverts": [  ]
}

###