

###

POST https://localhost:7018/api/V01/Authenticate/login
content-type: application/json

{
  "username": "jimmy",
  "password": "nordin_A1"
}

###
Respone av ovan är:
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiamltbXkiLCJqdGkiOiI3ZGYxNDAzYi0yMjhmLTQ5YjAtYjI4Ni0yMTQ5MzkxN2FjY2YiLCJleHAiOjE2NjMzMzY0MjMsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDIwMCJ9.y7mVBKtRVMso8Ap-_CA3uQrLakyOKCAQSVPPbGvztNo",
  "expiration": "2022-09-16T13:53:43Z"
}

###

POST https://localhost:7018/api/V01/Authenticate/register
content-type: application/json

{
  "username": "jimmy2",
  "email": "jimmy2@example.com",
  "password": "nordin_A1"
}


###
Respons av ovan ger:
{
  "status": "Success",
  "message": "User created successfully!"
}
